### ISSUE TITLE
MelonLoader folder needing permissions

### ISSUE THREAD

**Issue by theironspider** [LavaGang/MelonWiki#78]
i don't know if this should be here but when i try to delete it it says the folder needs permissions but when i hit continue it does not pop up with the permission screen

my OS is windows 11
the game is bloons td 6

**Comment by loukylor** [comment]
Yea this repo is for the wiki, not MelonLoader itself. So this issue should've been at the main MelonLoader page.

That said, having run into the same issue, make sure the game is closed and try deleting the files inside the MelonLoader folder and then delete the folder itself.

**Comment by loukylor** [comment]
Closing due to stale
